Repository prgrms-be-devcourse/NBE2-3-2-team4, pull requests merged in 2024-12, with the labels that each got.

#23 :bug:[Fix] : 주차장 이름 들어가지 않는 오류 수정
  src/main/java/com/team4/ttukttak_parking/domain/pklt/entity/Pklt.java
Labels: 🐞 fix

#35 ✨Feat]-#33-Cors 간단 설정 후 axios 테스트 완료
  src/main/java/com/team4/ttukttak_parking/config/WebConfig.java
  src/main/java/com/team4/ttukttak_parking/controller/PkltController.java
  src/main/java/com/team4/ttukttak_parking/domain/pklt/service/PkltService.java
  src/main/resources/application.yml
Labels: ✨ feature

#32 Feature/#26 주차장목록조회
  src/main/java/com/team4/ttukttak_parking/controller/AdminController.java
  src/main/java/com/team4/ttukttak_parking/domain/admin/service/AdminService.java
  src/main/java/com/team4/ttukttak_parking/domain/pklt/dto/PkltResponse.java
  src/main/java/com/team4/ttukttak_parking/domain/pklt/repository/PkltRepository.java
  src/main/java/com/team4/ttukttak_parking/domain/pkltstatus/repository/PkltStatusRepository.java
Labels: ✨ feature

#41 😎fix/#36-중복-데이터-제거
  src/main/java/com/team4/ttukttak_parking/domain/admin/service/AdminService.java
  src/main/java/com/team4/ttukttak_parking/domain/pklt/repository/PkltRepository.java
  src/main/java/com/team4/ttukttak_parking/domain/pklt/service/PkltService.java
  src/main/java/com/team4/ttukttak_parking/domain/pkltstatus/entity/PkltStatus.java
Labels: 🐞 fix

#45 🐛[Fix]#44 엔티티 수정
  src/main/java/com/team4/ttukttak_parking/controller/AdminController.java
  src/main/java/com/team4/ttukttak_parking/controller/MemberController.java
  src/main/java/com/team4/ttukttak_parking/controller/PkltController.java
  src/main/java/com/team4/ttukttak_parking/controller/TicketController.java
  src/main/java/com/team4/ttukttak_parking/domain/admin/service/AdminService.java
  src/main/java/com/team4/ttukttak_parking/domain/member/dto/MemberRequest.java
  src/main/java/com/team4/ttukttak_parking/domain/member/dto/MemberResponse.java
  src/main/java/com/team4/ttukttak_parking/domain/member/entity/Member.java
  src/main/java/com/team4/ttukttak_parking/domain/member/service/MemberService.java
  src/main/java/com/team4/ttukttak_parking/domain/order/dto/OrderRequest.java
  src/main/java/com/team4/ttukttak_parking/domain/order/dto/OrderResponse.java
  src/main/java/com/team4/ttukttak_parking/domain/order/entity/Order.java
  src/main/java/com/team4/ttukttak_parking/domain/order/repository/OrderRepository.java
  src/main/java/com/team4/ttukttak_parking/domain/order/service/OrderService.java
  src/main/java/com/team4/ttukttak_parking/domain/pklt/dto/PkltInfoResponse.java
  src/main/java/com/team4/ttukttak_parking/domain/pklt/dto/PkltResponse.java
  src/main/java/com/team4/ttukttak_parking/domain/pklt/dto/PkltStatusDetailsResponse.java
  src/main/java/com/team4/ttukttak_parking/domain/pklt/dto/PkltStatusResponse.java
  src/main/java/com/team4/ttukttak_parking/domain/pklt/entity/PkltInfo.java
  src/main/java/com/team4/ttukttak_parking/domain/pklt/repository/PkltRepository.java
  src/main/java/com/team4/ttukttak_parking/domain/pklt/service/PkltService.java
  src/main/java/com/team4/ttukttak_parking/domain/pkltstatus/dto/PkltStatusDetailsResponse.java
  src/main/java/com/team4/ttukttak_parking/domain/pkltstatus/dto/PkltStatusResponse.java
  src/main/java/com/team4/ttukttak_parking/domain/pkltstatus/entity/PkltStatusDetail.java
  src/main/java/com/team4/ttukttak_parking/domain/pkltstatus/entity/enums/ParkingStatus.java
  src/main/java/com/team4/ttukttak_parking/domain/pkltstatus/repository/PkltStatusDetailRepository.java
  src/main/java/com/team4/ttukttak_parking/domain/pkltstatus/repository/PkltStatusRepository.java
  src/main/java/com/team4/ttukttak_parking/domain/pkltstatus/service/PkltStatusService.java
  src/main/java/com/team4/ttukttak_parking/domain/ticket/dto/TicketRequestDto.java
  src/main/java/com/team4/ttukttak_parking/domain/ticket/dto/TicketResponseDto.java
  src/main/java/com/team4/ttukttak_parking/domain/ticket/entity/Ticket.java
  src/main/java/com/team4/ttukttak_parking/domain/ticket/repository/TicketOrderRepository.java
  src/main/java/com/team4/ttukttak_parking/domain/ticket/service/TicketService.java
Labels: 🔨 refactor, 🐞 fix

#43 ✨ [Feat] #38 Spring Security / Jwt
  build.gradle
  src/main/java/com/team4/ttukttak_parking/config/SecurityConfig.java
  src/main/java/com/team4/ttukttak_parking/config/SwaggerConfig.java
  src/main/java/com/team4/ttukttak_parking/controller/AdminController.java
  src/main/java/com/team4/ttukttak_parking/controller/AuthController.java
  src/main/java/com/team4/ttukttak_parking/controller/MemberController.java
  src/main/java/com/team4/ttukttak_parking/domain/member/dto/MemberRequest.java
  src/main/java/com/team4/ttukttak_parking/domain/member/entity/Member.java
  src/main/java/com/team4/ttukttak_parking/domain/member/entity/enums/LoginTypes.java
  src/main/java/com/team4/ttukttak_parking/domain/member/entity/enums/MemberRoles.java
  src/main/java/com/team4/ttukttak_parking/domain/member/service/MemberService.java
  src/main/java/com/team4/ttukttak_parking/domain/ticket/entity/Ticket.java
  src/main/java/com/team4/ttukttak_parking/global/exception/GlobalExceptionHandler.java
  src/main/java/com/team4/ttukttak_parking/global/exception/JWTCustomException.java
  src/main/java/com/team4/ttukttak_parking/security/dto/TokenRequest.java
  src/main/java/com/team4/ttukttak_parking/security/dto/TokenResponse.java
  src/main/java/com/team4/ttukttak_parking/security/handler/JWTAccessDeniedHandler.java
  src/main/java/com/team4/ttukttak_parking/security/handler/JWTAuthenticationEntryPoint.java
  src/main/java/com/team4/ttukttak_parking/security/handler/JWTFilter.java
  src/main/java/com/team4/ttukttak_parking/security/handler/JwtFilterExceptionHandler.java
  src/main/java/com/team4/ttukttak_parking/security/service/CustomUserDetailService.java
  src/main/java/com/team4/ttukttak_parking/security/util/TokenProvider.java
  src/main/resources/application.yml
Labels: 🐞 fix

#47 ✨ [Feat] #46 주차장 별 주차권 데이터 생성
  build.gradle
  src/main/java/com/team4/ttukttak_parking/config/SecurityConfig.java
  src/main/java/com/team4/ttukttak_parking/controller/AdminController.java
  src/main/java/com/team4/ttukttak_parking/domain/pklt/repository/PkltInfoRepository.java
  src/main/java/com/team4/ttukttak_parking/domain/ticket/entity/Ticket.java
  src/main/java/com/team4/ttukttak_parking/domain/ticket/service/TicketService.java
  src/main/java/com/team4/ttukttak_parking/global/exception/ErrorCode.java
  src/main/java/com/team4/ttukttak_parking/security/handler/JWTFilter.java
  src/main/resources/application.yml
Labels: ✨ feature

#49 ✨ [Feat] #48 Admin 회원가입
  src/main/java/com/team4/ttukttak_parking/config/SecurityConfig.java
  src/main/java/com/team4/ttukttak_parking/controller/AdminController.java
  src/main/java/com/team4/ttukttak_parking/controller/AuthController.java
  src/main/java/com/team4/ttukttak_parking/domain/admin/entity/Admin.java
  src/main/java/com/team4/ttukttak_parking/domain/member/entity/Member.java
  src/main/java/com/team4/ttukttak_parking/domain/member/service/MemberService.java
  src/main/java/com/team4/ttukttak_parking/security/handler/JWTFilter.java
Labels: ✨ feature

#53 [feat] 주차권 주문 구현
  src/main/java/com/team4/ttukttak_parking/controller/OrderController.java
  src/main/java/com/team4/ttukttak_parking/domain/order/dto/OrderRequest.java
  src/main/java/com/team4/ttukttak_parking/domain/order/entity/Order.java
  src/main/java/com/team4/ttukttak_parking/domain/order/service/OrderService.java
  src/main/java/com/team4/ttukttak_parking/domain/pklt/entity/Pklt.java
  src/main/java/com/team4/ttukttak_parking/domain/pkltstatus/entity/PkltStatus.java
  src/main/java/com/team4/ttukttak_parking/global/exception/ErrorCode.java
Labels: ✨ feature

#54 ✨[Feat] #50 혼잡도 낮은 순으로 정렬 후 조회
  src/main/java/com/team4/ttukttak_parking/controller/PkltController.java
  src/main/java/com/team4/ttukttak_parking/domain/pklt/dto/PkltRequest.java
  src/main/java/com/team4/ttukttak_parking/domain/pklt/dto/PkltResponse.java
  src/main/java/com/team4/ttukttak_parking/domain/pklt/service/PkltService.java
Labels: ✨ feature

#57 🔨 [Refactor] 주차장,티켓 기본 데이터 추가 로직 수정 및 전체적인 리팩토링
  src/main/java/com/team4/ttukttak_parking/controller/AdminController.java
  src/main/java/com/team4/ttukttak_parking/controller/AuthController.java
  src/main/java/com/team4/ttukttak_parking/controller/MemberController.java
  src/main/java/com/team4/ttukttak_parking/controller/OrderController.java
  src/main/java/com/team4/ttukttak_parking/controller/PkltController.java
  src/main/java/com/team4/ttukttak_parking/controller/TicketController.java
  src/main/java/com/team4/ttukttak_parking/domain/admin/service/AdminService.java
  src/main/java/com/team4/ttukttak_parking/domain/member/dto/MemberResponse.java
  src/main/java/com/team4/ttukttak_parking/domain/member/service/MemberService.java
  src/main/java/com/team4/ttukttak_parking/domain/order/dto/OrderRequest.java
  src/main/java/com/team4/ttukttak_parking/domain/order/dto/OrderResponse.java
  src/main/java/com/team4/ttukttak_parking/domain/order/entity/Order.java
  src/main/java/com/team4/ttukttak_parking/domain/order/service/OrderService.java
  src/main/java/com/team4/ttukttak_parking/domain/pklt/dto/PkltInfoResponse.java
  src/main/java/com/team4/ttukttak_parking/domain/pklt/dto/PkltResponse.java
  src/main/java/com/team4/ttukttak_parking/domain/pklt/entity/Pklt.java
  src/main/java/com/team4/ttukttak_parking/domain/pklt/entity/PkltInfo.java
  src/main/java/com/team4/ttukttak_parking/domain/pklt/repository/PkltInfoRepository.java
  src/main/java/com/team4/ttukttak_parking/domain/pklt/repository/PkltRepository.java
  src/main/java/com/team4/ttukttak_parking/domain/pklt/service/PkltService.java
  src/main/java/com/team4/ttukttak_parking/domain/pkltstatus/dto/PkltStatusDetailsResponse.java
  src/main/java/com/team4/ttukttak_parking/domain/pkltstatus/dto/PkltStatusResponse.java
  src/main/java/com/team4/ttukttak_parking/domain/pkltstatus/entity/PkltStatus.java
  src/main/java/com/team4/ttukttak_parking/domain/pkltstatus/repository/PkltStatusRepository.java
  src/main/java/com/team4/ttukttak_parking/domain/pkltstatus/service/PkltStatusService.java
  src/main/java/com/team4/ttukttak_parking/domain/ticket/dto/TicketRequestDto.java
  src/main/java/com/team4/ttukttak_parking/domain/ticket/dto/TicketResponseDto.java
  src/main/java/com/team4/ttukttak_parking/domain/ticket/repository/TicketRepository.java
  src/main/java/com/team4/ttukttak_parking/domain/ticket/service/TicketService.java
  src/main/java/com/team4/ttukttak_parking/security/dto/TokenResponse.java
  src/main/resources/application.yml
Labels: 🔨 refactor, 🐞 fix

#65 ✨ [Feat] 입차
  src/main/java/com/team4/ttukttak_parking/controller/OrderController.java
  src/main/java/com/team4/ttukttak_parking/controller/PkltController.java
  src/main/java/com/team4/ttukttak_parking/domain/order/dto/OrderResponse.java
  src/main/java/com/team4/ttukttak_parking/domain/order/entity/Order.java
  src/main/java/com/team4/ttukttak_parking/domain/order/repository/OrderRepository.java
  src/main/java/com/team4/ttukttak_parking/domain/order/service/OrderService.java
  src/main/java/com/team4/ttukttak_parking/domain/pklt/dto/PkltResponse.java
  src/main/java/com/team4/ttukttak_parking/domain/pklt/entity/Pklt.java
  src/main/java/com/team4/ttukttak_parking/domain/pklt/service/PkltService.java
  src/main/java/com/team4/ttukttak_parking/domain/pkltstatus/entity/PkltStatusDetail.java
  src/main/java/com/team4/ttukttak_parking/domain/ticket/dto/TicketResponse.java
  src/main/java/com/team4/ttukttak_parking/global/exception/ErrorCode.java
Labels: ✨ feature

#71 ✨ [Feat] 주차권 기록 상세 조회
  src/main/java/com/team4/ttukttak_parking/controller/OrderController.java
  src/main/java/com/team4/ttukttak_parking/domain/order/dto/OrderResponse.java
  src/main/java/com/team4/ttukttak_parking/domain/order/service/OrderService.java
  src/main/java/com/team4/ttukttak_parking/domain/pklt/entity/PkltInfo.java
  src/main/java/com/team4/ttukttak_parking/global/exception/ErrorCode.java
Labels: ✨ feature

#75 Feature/#74 주차권리스트조회
  src/main/java/com/team4/ttukttak_parking/controller/PkltController.java
  src/main/java/com/team4/ttukttak_parking/domain/pklt/service/PkltService.java
  src/main/java/com/team4/ttukttak_parking/domain/ticket/dto/TicketResponse.java
  src/main/java/com/team4/ttukttak_parking/domain/ticket/repository/TicketRepository.java
Labels: ✨ feature

#83 Feature/#100 주차장결제정보확인
  src/main/java/com/team4/ttukttak_parking/controller/PkltController.java
  src/main/java/com/team4/ttukttak_parking/domain/member/repository/CarRepository.java
  src/main/java/com/team4/ttukttak_parking/domain/pklt/dto/PkltResponse.java
  src/main/java/com/team4/ttukttak_parking/domain/pklt/service/PkltService.java
  src/main/java/com/team4/ttukttak_parking/global/exception/AccessDeniedException.java
  src/main/java/com/team4/ttukttak_parking/global/exception/ErrorCode.java
Labels: ✨ feature
